name: Run tests

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{steps.load.outputs.strategy}}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: colcon/ci
      - id: load
        run: echo "strategy=$(echo $(cat strategy.json))" >> $GITHUB_OUTPUT

  pytest:
    needs: [setup]
    strategy: ${{fromJson(needs.setup.outputs.strategy)}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - run: |
          find * -type f | xargs sed -i 's/template-package/colcon-package-name/g'
          find * -type f | xargs sed -i 's/template_package/colcon_package_name/g'
          mv template_package colcon_package_name
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}
      - uses: colcon/ci@v1
